# Generated by Django 4.2 on 2023-10-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('image_id', models.TextField()),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='image',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
