# Generated by Django 4.2 on 2023-10-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_drivemodel_remove_imagemodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PublishedShortTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publisheditemmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.TextField()),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField(null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PublishedLongTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publisheditemmodel')),
            ],
        ),
        migrations.AddField(
            model_name='publisheditemmodel',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publishedmodel'),
        ),
        migrations.CreateModel(
            name='PublishedImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=255)),
                ('image_id', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publisheditemmodel')),
            ],
        ),
    ]
