# Generated by Django 4.2 on 2023-10-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_publisheditemmodel_publishedshorttextmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisheditemmodel',
            name='content_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
