# Generated by Django 4.2 on 2023-10-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_publisheditemmodel_content_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisheditemmodel',
            name='col_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
