# Generated by Django 4.2 on 2023-10-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_publisheditemmodel_col_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='is_blog_mode',
            field=models.BooleanField(default=False),
        ),
    ]
