# Generated by Django 4.2 on 2023-10-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_pagemodel_name_pagemodel_is_blog_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
