# Generated by Django 4.2 on 2023-10-29 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_richtextmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedRichTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publisheditemmodel')),
            ],
        ),
    ]
